// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfHRPPkQTRHTtR8br1AveTdHXWNflkm4k',
    appId: '1:898871786750:web:84403be761776ee1a9b9af',
    messagingSenderId: '898871786750',
    projectId: 'kanbanflutter',
    authDomain: 'kanbanflutter.firebaseapp.com',
    storageBucket: 'kanbanflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDcRIDm7Q2iEP2doox0j2hAtL-0bJnvvI',
    appId: '1:898871786750:android:6cbf95272c2eed56a9b9af',
    messagingSenderId: '898871786750',
    projectId: 'kanbanflutter',
    storageBucket: 'kanbanflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeeCkBB8brmmnznnxxDevc6YgMBk2eWpo',
    appId: '1:898871786750:ios:0a8bb5b40e11a7f4a9b9af',
    messagingSenderId: '898871786750',
    projectId: 'kanbanflutter',
    storageBucket: 'kanbanflutter.appspot.com',
    iosClientId: '898871786750-3fgmtn58h3t29b7obv39ms5iur3kd8vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kanbanBoardFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeeCkBB8brmmnznnxxDevc6YgMBk2eWpo',
    appId: '1:898871786750:ios:0a8bb5b40e11a7f4a9b9af',
    messagingSenderId: '898871786750',
    projectId: 'kanbanflutter',
    storageBucket: 'kanbanflutter.appspot.com',
    iosClientId: '898871786750-3fgmtn58h3t29b7obv39ms5iur3kd8vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kanbanBoardFlutter',
  );
}
